(function () {
  'use strict';
  var paper = document.getElementById('paper');
  var title = document.getElementById('documentTitle');
  var fileInput = document.getElementById('fileInput');
  var imageInput = document.getElementById('imageInput');
  var saveState = document.getElementById('saveState');
  var storageKey = 'switch-docs';
  var repository = 'DigitalRage/switch-docs';
  var repositoryBranch = 'main';
  var currentPath = 'documents/' + ((title.value || 'untitled-document').replace(/[^a-z0-9-_]+/gi, '-').toLowerCase() || 'untitled-document') + '.html';
  var savedSelection;

  function selectEditor() { paper.focus(); }
  function rememberSelection() { var selection = window.getSelection(); if (selection.rangeCount) savedSelection = selection.getRangeAt(0); }
  function restoreSelection() { selectEditor(); if (savedSelection) { var selection = window.getSelection(); selection.removeAllRanges(); selection.addRange(savedSelection); } }
  function exec(command, value) { restoreSelection(); document.execCommand(command, false, value || null); updateStats(); scheduleSave(); }
  function scheduleSave() { saveState.textContent = 'Saving...'; clearTimeout(window.saveTimer); window.saveTimer = setTimeout(saveLocal, 500); }
  function saveLocal() { localStorage.setItem(storageKey, JSON.stringify({ title: title.value, html: paper.innerHTML })); saveState.textContent = 'Saved locally'; }
  var collaborationSocket;
  var applyingRemote = false;
  function encodedDocument() { return btoa(unescape(encodeURIComponent('<!doctype html><meta charset="utf-8"><title>' + escapeHtml(title.value) + '</title>' + paper.innerHTML))); }
  function githubRequest(path, options) { options = options || {}; options.headers = Object.assign({ Accept:'application/vnd.github+json' }, options.headers || {}); return fetch('https://api.github.com/repos/' + repository + path, options); }
  function commitToRepository() {
    if (collaborationSocket && collaborationSocket.readyState === WebSocket.OPEN) { collaborationSocket.send(JSON.stringify({ type:'update', path:currentPath, title:title.value, html:paper.innerHTML })); saveState.textContent = 'Shared live'; return Promise.resolve(true); }
    saveState.textContent = 'Saved locally (server offline)'; return Promise.resolve(false);
  }
  function connectCollaboration() { var configuredEndpoint = document.querySelector('meta[name="collaboration-endpoint"]').content.trim(); if (!window.WebSocket || !location.host || (!configuredEndpoint && /\.github\.io$/i.test(location.hostname))) { document.getElementById('collaborationState').textContent = 'Server required'; return; } var endpoint = configuredEndpoint || ((location.protocol === 'https:' ? 'wss://' : 'ws://') + location.host); collaborationSocket = new WebSocket(endpoint + '/collab'); collaborationSocket.addEventListener('open', function () { document.getElementById('collaborationState').textContent = 'Live'; collaborationSocket.send(JSON.stringify({ type:'join', path:currentPath })); }); collaborationSocket.addEventListener('message', function (event) { var message = JSON.parse(event.data); if (message.type !== 'update') return; applyingRemote = true; title.value = message.title; paper.innerHTML = message.html; saveLocal(); updateStats(); applyingRemote = false; saveState.textContent = 'Updated live'; }); collaborationSocket.addEventListener('close', function () { document.getElementById('collaborationState').textContent = 'Offline'; }); collaborationSocket.addEventListener('error', function () { document.getElementById('collaborationState').textContent = 'Offline'; }); }
  function reconnectCollaboration() { if (collaborationSocket) collaborationSocket.close(); else connectCollaboration(); }
  function repositoryFilePath() { return 'documents/' + safeName() + '.html'; }
  function loadHome() {
    document.getElementById('editorView').hidden = true; document.getElementById('homeView').hidden = false;
    var grid = document.getElementById('documentGrid'); var notice = document.getElementById('homeNotice'); grid.innerHTML = '<div class="loading-card">Loading repository documents...</div>'; notice.textContent = '';
    Promise.all([githubRequest('/contents?ref=' + repositoryBranch).then(function (response) { if (!response.ok) throw new Error('Repository unavailable'); return response.json(); }), githubRequest('/contents/documents?ref=' + repositoryBranch).then(function (response) { return response.ok ? response.json() : []; })]).then(function (lists) {
      var docs = lists[0].concat(lists[1]).filter(function (file) { return file.type === 'file' && /\.(html?|docx)$/i.test(file.name) && file.name !== 'index.html'; }).filter(function (file, index, all) { return all.findIndex(function (item) { return item.path === file.path; }) === index; }); grid.innerHTML = '';
      if (!docs.length) { grid.innerHTML = '<div class="loading-card">No repository documents yet. Create one to get started.</div>'; return; }
      docs.forEach(function (file) { var card = document.createElement('button'); card.className = 'document-card'; card.innerHTML = '<div class="document-preview">Loading preview...</div><div class="document-meta"><span class="document-icon">▤</span><span class="document-name">' + escapeHtml(file.name) + '</span></div><div class="document-date">Open from current repository</div>'; card.addEventListener('click', function () { openRepositoryFile(file); }); grid.appendChild(card); loadCardPreview(card, file); });
    }).catch(function () { grid.innerHTML = '<div class="loading-card">Connect GitHub to display repository documents.</div>'; notice.textContent = 'The repository is read-only until a GitHub token is connected.'; });
  }
  function loadCardPreview(card, file) { fetch(file.download_url).then(function (response) { return response.text(); }).then(function (html) { var preview = card.querySelector('.document-preview'); var parsed = new DOMParser().parseFromString(html, 'text/html'); preview.innerHTML = parsed.body ? parsed.body.innerHTML : escapeHtml(html); }); }
  function openRepositoryFile(file) { fetch(file.download_url).then(function (response) { return response.text(); }).then(function (html) { var parsed = new DOMParser().parseFromString(html, 'text/html'); title.value = (parsed.title || file.name).replace(/\.html?$/i, ''); paper.innerHTML = parsed.body ? parsed.body.innerHTML : '<p>' + escapeHtml(html) + '</p>'; currentPath = file.path; reconnectCollaboration(); saveLocal(); document.getElementById('homeView').hidden = true; document.getElementById('editorView').hidden = false; updateStats(); }); }
  function showEditor() { document.getElementById('homeView').hidden = true; document.getElementById('editorView').hidden = false; }
  function updateStats() { var text = paper.innerText.trim(); var words = text ? text.split(/\s+/).length : 0; var pages = Math.max(1, Math.ceil(paper.scrollHeight / 1056)); document.getElementById('wordCount').textContent = words + (words === 1 ? ' word' : ' words'); document.getElementById('pageCount').textContent = 'Page ' + pages + ' of ' + pages; }
  function download(name, data, type) { var blob = new Blob([data], { type:type }); var link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = name; link.click(); setTimeout(function () { URL.revokeObjectURL(link.href); }, 1000); }
  function safeName() { return (title.value || 'untitled-document').replace(/[^a-z0-9-_]+/gi, '-').replace(/^-|-$/g, '').toLowerCase() || 'untitled-document'; }
  function escapeHtml(value) { return value.replace(/[&<>"']/g, function (character) { return ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' })[character]; }); }
  function exportHtml() { var html = '<!doctype html><meta charset="utf-8"><title>' + escapeHtml(title.value) + '</title><style>body{font:16px Arial;max-width:816px;margin:40px auto;line-height:1.55}img{max-width:100%}table{border-collapse:collapse;width:100%}td{border:1px solid #999;padding:8px}</style>' + paper.innerHTML; download(safeName() + '.html', html, 'text/html'); }
  function docxXml() { var content = paper.innerHTML.replace(/<br\s*\/?>(?!<\/p>)/gi, '<w:br/>').replace(/<p[^>]*>/gi, '<w:p>').replace(/<\/p>/gi, '</w:p>').replace(/<strong>|<b>/gi, '<w:r><w:rPr><w:b/></w:rPr><w:t>').replace(/<\/strong>|<\/b>/gi, '</w:t></w:r>').replace(/<em>|<i>/gi, '<w:r><w:rPr><w:i/></w:rPr><w:t>').replace(/<\/em>|<\/i>/gi, '</w:t></w:r>').replace(/<u>/gi, '<w:r><w:rPr><w:u w:val="single"/></w:rPr><w:t>').replace(/<\/u>/gi, '</w:t></w:r>').replace(/<li>/gi, '<w:p><w:r><w:t>• </w:t></w:r>').replace(/<\/li>/gi, '</w:r></w:p>').replace(/<ul>|<\/ul>|<ol>|<\/ol>/gi, ''); return content.replace(/<[^>]+>/g, function (tag) { return tag.indexOf('<w:') === 0 ? tag : ''; }); }
  function exportDocx() { if (!window.JSZip) { alert('DOCX library is still loading. Try again in a moment.'); return; } var zip = new JSZip(); var documentXml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>' + docxXml() + '<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:document>'; zip.file('[Content_Types].xml', '<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>'); zip.file('_rels/.rels', '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>'); zip.file('word/document.xml', documentXml); zip.generateAsync({ type:'blob' }).then(function (blob) { var link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = safeName() + '.docx'; link.click(); }); }
  function importDocx(file) { JSZip.loadAsync(file).then(function (zip) { return zip.file('word/document.xml').async('string'); }).then(function (xml) { var doc = new DOMParser().parseFromString(xml, 'application/xml'); var paragraphs = Array.prototype.slice.call(doc.getElementsByTagName('w:p')); paper.innerHTML = paragraphs.map(function (paragraph) { var text = Array.prototype.slice.call(paragraph.getElementsByTagName('w:t')).map(function (node) { return node.textContent; }).join(''); return '<p>' + escapeHtml(text) + '</p>'; }).join('') || '<p><br></p>'; scheduleSave(); updateStats(); }).catch(function () { alert('This DOCX could not be opened.'); }); }
  function importFile(file) { if (!file) return; if (/\.docx$/i.test(file.name)) return importDocx(file); var reader = new FileReader(); reader.onload = function () { if (/\.html?$/i.test(file.name)) { paper.innerHTML = new DOMParser().parseFromString(reader.result, 'text/html').body.innerHTML; } else paper.innerText = reader.result; scheduleSave(); updateStats(); }; reader.readAsText(file); }
  function insertTable() { var rows = parseInt(prompt('Rows:', '3'), 10); var columns = parseInt(prompt('Columns:', '3'), 10); if (!rows || !columns || rows > 20 || columns > 10) return; var table = '<table><tbody>'; for (var row = 0; row < rows; row++) { table += '<tr>'; for (var column = 0; column < columns; column++) table += '<td><br></td>'; table += '</tr>'; } restoreSelection(); document.execCommand('insertHTML', false, table + '</tbody></table><p><br></p>'); scheduleSave(); }
  function replaceAll() { var find = document.getElementById('findInput').value; if (!find) return; paper.innerHTML = paper.innerHTML.split(find).join(document.getElementById('replaceInput').value); scheduleSave(); updateStats(); }
  paper.addEventListener('input', function () { updateStats(); scheduleSave(); if (!applyingRemote) commitToRepository(); }); paper.addEventListener('mouseup', rememberSelection); paper.addEventListener('keyup', rememberSelection);
  title.addEventListener('input', function () { if (currentPath === 'documents/untitled-document.html') { currentPath = repositoryFilePath(); if (collaborationSocket) collaborationSocket.close(); } scheduleSave(); });
  document.querySelectorAll('[data-command]').forEach(function (button) { button.addEventListener('click', function () { exec(button.dataset.command); }); });
  document.querySelectorAll('[data-action]').forEach(function (button) { button.addEventListener('click', function () { var action = button.dataset.action; if (action === 'home') loadHome(); if (action === 'refresh-home') loadHome(); if (action === 'connect') document.getElementById('settingsDialog').showModal(); if (action === 'new' && confirm('Start a new document?')) { paper.innerHTML = '<p><br></p>'; title.value = 'Untitled document'; currentPath = repositoryFilePath(); showEditor(); scheduleSave(); } if (action === 'open') fileInput.click(); if (action === 'save') { saveLocal(); commitToRepository(); } if (action === 'download') exportDocx(); if (action === 'print') window.print(); if (action === 'link') { var url = prompt('Enter a URL:', 'https://'); if (url) exec('createLink', url); } if (action === 'image') imageInput.click(); if (action === 'table') insertTable(); if (action === 'checklist') exec('insertHTML', '<ul><li class="check-item">Checklist item</li></ul>'); if (action === 'clear') exec('removeFormat'); if (action === 'find') document.getElementById('findDialog').showModal(); if (action === 'fullscreen') document.body.classList.toggle('fullscreen'); if (action === 'stats') { document.getElementById('statsText').textContent = document.getElementById('wordCount').textContent + ', ' + paper.innerText.length + ' characters.'; document.getElementById('statsDialog').showModal(); } if (action === 'help') alert('OpenPage Docs supports rich text, lists, links, images, tables, tabs, printing, local autosave, GitHub autosave, HTML export, DOCX export, and DOCX import.'); if (action === 'share') { if (navigator.clipboard) navigator.clipboard.writeText(location.href); alert('This page URL is ready to share.'); } if (action === 'add-tab') { var tabName = prompt('Name this tab:', 'New tab'); if (tabName) { var tab = document.createElement('button'); tab.className = 'tab'; tab.innerHTML = '▤ <span>' + escapeHtml(tabName) + '</span>'; document.getElementById('tabList').appendChild(tab); } } if (action === 'outline') alert('Outline is built from your headings. Use Heading 1, Heading 2, or Heading 3 in the style menu.'); }); });
  fileInput.addEventListener('change', function () { importFile(fileInput.files[0]); fileInput.value = ''; }); imageInput.addEventListener('change', function () { var file = imageInput.files[0]; if (!file) return; var reader = new FileReader(); reader.onload = function () { restoreSelection(); exec('insertImage', reader.result); }; reader.readAsDataURL(file); });
  document.getElementById('fontName').addEventListener('change', function (event) { exec('fontName', event.target.value); }); document.getElementById('fontSize').addEventListener('change', function (event) { exec('fontSize', event.target.value); }); document.getElementById('textColor').addEventListener('change', function (event) { exec('foreColor', event.target.value); }); document.getElementById('highlightColor').addEventListener('change', function (event) { exec('hiliteColor', event.target.value); }); document.getElementById('blockStyle').addEventListener('change', function (event) { exec('formatBlock', event.target.value); }); document.getElementById('zoom').addEventListener('change', function (event) { paper.style.zoom = event.target.value.replace('%', '') / 100; });
  document.getElementById('replaceAll').addEventListener('click', replaceAll); document.getElementById('findNext').addEventListener('click', function () { var find = document.getElementById('findInput').value; if (find) window.find(find); }); document.querySelectorAll('[data-close-dialog]').forEach(function (button) { button.addEventListener('click', function () { button.closest('dialog').close(); }); });
  document.querySelectorAll('[data-close-dialog]').forEach(function (button) { button.addEventListener('click', function () { button.closest('dialog').close(); }); });
  document.getElementById('deployButton').addEventListener('click', function () { document.getElementById('deployDialog').showModal(); });
  setInterval(function () { if (!document.getElementById('editorView').hidden) { saveLocal(); commitToRepository(); } }, 180000);
  var existing = localStorage.getItem(storageKey); if (existing) { try { var data = JSON.parse(existing); title.value = data.title || title.value; paper.innerHTML = data.html || paper.innerHTML; currentPath = repositoryFilePath(); } catch (error) {} } updateStats(); connectCollaboration(); loadHome();
}());